name: "P6 GHA: Spellcheck"
description: "P6 GHA: Spellcheck"
author: "Philip M. Gollucci"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: p6m7g8-actions/checkout@main

    - name: "Generate cspell.json from VSCode settings"
      shell: bash
      run: |
        mkdir -p .github/tmp
        jq '{ version: "0.2", words: .["cSpell.words"] }' .vscode/settings.json > .github/tmp/cspell.json

    - name: "Spellcheck"
      uses: streetsidesoftware/cspell-action@v7.2.0
      with:
        incremental_files_only: false
        inline: warning
        treat_flagged_words_as_errors: false
        strict: true
        suggestions: false
        verbose: true
        check_dot_files: explicit
        use_cspell_files: true
        config: .github/tmp/cspell.json
        report: all
